import requests
... 
... 
... class CloudSecurity:
... 
... 
...     def check_hash(self,file_hash):
... 
...         try:
... 
...             response=requests.post(
...                 "https://your-cloud-server.com/check",
...                 json={
...                     "hash":file_hash
...                 }
...             )
... 
... 
...             return response.json()
... 
... 
...         except:
... 
...             return {
...                 "status":"offline"
